config/routes.rb
PrettyReports::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users
  devise_scope :user do get '/users/sign_out' => 'devise/sessions#destroy' end

  root to: "home#index"

  get '/home' => 'home#index'
  get '/static-pages/about-us' => 'static_pages#about_us'
  get '/static-pages/welcome' => 'static_pages#welcome', as: 'welcome_page'

  resources :reports do
    member do
      get 'download'
      get 'download_available', path: 'download-available'
    end
  end

  resources :users

  resources :imports

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id          :integer         not null, primary key
#  report_type :string(255)
#  title       :string(255)
#  subtitle    :string(255)
#  content1    :string(255)
#  content2    :string(255)
#  content3    :string(255)
#  user_id     :integer         not null
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Report < ActiveRecord::Base

  attr_accessible :title, :subtitle, :content1, :content2, :content3,
    :report_type, :user_id

  validates :report_type, :presence => true
  has_many :items, order: "position ASC", dependent: :delete_all

  belongs_to :user
  validates :user_id, :presence => true

  def as_json(options={})
    result = super(
      {except: [:created_at, :updated_at]}.merge(options))
    result[:items] = self.items.as_json()
    result
  end

  # Takes the REST URL for a report and transforms it into a printable PDF
  # @pram url REST URL to reach the report
  # @returns printable PDF binary object
  def self.as_pdf(url)
    @kit = PDFKit.new(url, self.wkhtmltopdf_params)
    @kit.to_pdf
  end

  # Returns the name that this report should have if serialized to a filename
  # @returns filename, sanitized
  def to_filename()
    filename = self.title
    if filename == "" 
      filename = "report"
    end

    filename.gsub(/[^0-9A-Za-z.\-]/, '_')
  end
  
  private

  # Internal: This logic was extracted here due to platform compatibility issues
  # On MacOS these parameters does not work, those who are using OSX need to add
  # an initializer (and not commit it) opening this class and changing this
  # method.
  def self.wkhtmltopdf_params
    {}
  end

end

app/controllers/reports_controller.rb
require 'net/http'

class ReportsController < ApplicationController

  before_filter :authenticate_user!, :except => [:show]

  def index
    @reports = current_user.reports.order("created_at")
  end

  # This method is particulary complex because it's the one accessed by
  # PDFKit. PDFKit cannot log in but we cannot take out access control from
  # the method because it would allow any non authenticated user to 
  # access every report, even those that are not his own. So the approach
  # taken is this one:
  #
  # 1) When accessing .pdf:
  # 
  # Full access control is enforced. Additionally, a token is generated
  # for PDFKit that uses it as a querystring parameter to generate the report 
  # as HTML and print the PDF.
  #
  # 2) When accessing .html:
  # 
  # In the case of a request without a token, full access control is enforced.
  # In the case of a request with a token, the token database is accessed
  # and then access control is enforced employing the user that owns the token.
  def show
    respond_to do |format|
      format.html do
        # If user is not logged in, then check if it's PDFKit using a token
        tokenizer_uid = params[:tokenizer_uid]      
        
        if tokenizer_uid.blank?
          authenticate_user!
        else
          tokenizer = Tokenizer.find_by_uid(tokenizer_uid)
          sign_in(:user, tokenizer.user)
        end
        @report = current_user.reports.find(params[:id])
      end
      format.pdf do
        # User must be logged in to use this feature
        authenticate_user!

        @report = current_user.reports.find(params[:id])

        # Get a token for PDFKit to use
        tokenizer = Tokenizer.create!(:user_id => current_user.id)
        # Insert the token in the URL
        url = report_url(@report) + "?tokenizer_uid=#{tokenizer}"

        # Send URL to PDFKit
        pdf = Report.as_pdf(url)
        send_data pdf, :filename => @report.to_filename + ".pdf"
      end
    end
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(params[:report].except(:items))
    
    # //FIXME Eliminate "\n" because of a bug in the template
    @report.title = @report.title.gsub("\n", "").strip
    
    @report.items = @report.items.build(params[:report][:items])

    @report.user_id = current_user.id

    @report.save

    render json: @report.to_json(include: :items)
  end

  def edit
    @report = current_user.reports.find(params[:id])
  end

  def update
    @report = current_user.reports.find(params[:report][:id])
    @report.attributes = params[:report].except(
      :items, :id, :user_id)

    # //FIXME Eliminate "\n" because of a bug in the template
    @report.title = @report.title.gsub("\n", "").strip

    @report.items = @report.items.build(params[:report][:items])

    @report.save

    render json: @report.to_json(include: :items)
  end

  def destroy
    @report = current_user.reports.find(params[:id])
    @report.destroy

    redirect_to reports_url
  end

end

app/views/reports/edit.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    // Initialize the js for this particular page when the DOM is ready.
    $(document).ready(function() {
      app.reports.initialize({
        report: <%= @report.to_json.html_safe %>
      });
    });
  </script>
<% end %>

<% provide(:page_id, "reports-edit-page") %>
<% provide(:page_class, "scroll-aware") %>

<%= render 'reports/common/input_tool' %>

<%= render 'reports/sprint_release/sprint_release' %>

<div id="import-button" class="js-import-button import-button">
  <i></i><span>Import</span>
</div>

<div class="js-save-button save-button">
  <i></i><span>Save</span>
</div>

<div class="js-download-button download-button">
  <i></i><span>Download</span>
</div>

app/views/reports/index.html.erb
<% provide(:title, 'My Reports') %>
<% provide(:page_id, "my-reports-page") %>

<div class="container">

  <table class="custom-table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Report Type</th>
        <th>Created</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @reports.each do |report| %>
        <tr>
          <td><%= report.title %></td>
          <td><%= human_report_type report.report_type %></td>
          <td><%= time_ago_in_words report.created_at %> ago</td>
          <td class="actions">
            <%= link_to '', edit_report_path(report) , class: 'edit-icon' %>
            <%= link_to '', report, method: :delete,
              data: { :confirm => 'Are you sure you want to delete the report' },
              class: 'delete-icon' %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

<div class="actions-toolbar-wrapper">
  <div class="actions-toolbar">

    <a onclick="window.location='<%= new_report_path %>'"
      class="button white-button js-new-button" value="New">

      New Sprint Release<i class="button-icon-plus-right"></i>
    </a>
    <a class="button white-button coming-soon">
      New Sprint Definition<i class="button-icon-plus-right"></i>
    </a>
    <a class="button white-button coming-soon">
      Daily Email<i class="button-icon-plus-right"></i>
    </a>

  </div>
</div>

app/views/reports/new.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    // Initialize the js for this particular page when the DOM is ready.
    $(document).ready(function() {
      app.reports.initialize({});
    });
  </script>
<% end %>

<% provide(:page_id, "reports-new-page") %>
<% provide(:page_class, "scroll-aware") %>

<%= render 'reports/common/input_tool' %>

<%= render 'reports/sprint_release/sprint_release' %>

<div id="import-button" class="js-import-button import-button">
  <i></i><span>Import</span>
</div>

<div id="save-button" class="js-save-button save-button">
  <i></i><span>Save</span>
</div>

<div id="download-button" class="js-download-button download-button">
  <i></i><span>Download</span>
</div>

app/views/reports/show.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    // Initialize the js for this particular page when the DOM is ready.
    $(document).ready(function() {
      app.reports.initialize({
        report: <%= @report.to_json.html_safe %>
      });
    });
  </script>
<% end %>

<% provide(:page_id, "reports-show-page") %>

<% if @report.report_type == 'sprint-definition' %>
  <%= render 'reports/sprint_definition/sprint_definition',
    locals: {report: @report} %>

<% elsif @report.report_type == 'sprint-release' %>
  <%= render 'reports/sprint_release/sprint_release',
    locals: {report: @report} %>

<% end %>

<%= @data %>