config/routes.rb
PrettyReports::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users
  devise_scope :user do get '/users/sign_out' => 'devise/sessions#destroy' end

  root to: "home#index"

  get '/home' => 'home#index'
  get '/static-pages/about-us' => 'static_pages#about_us'
  get '/static-pages/welcome' => 'static_pages#welcome', as: 'welcome_page'

  resources :reports do
    member do
      get 'download'
      get 'download_available', path: 'download-available'
    end
  end

  resources :users

  resources :imports

end

app/views/layouts/_footer.html.erb
<section id="page-footer">
  <div class="left-links">
  </div>

  <div class="copy-right">Copyright 2012 - ™ Pretty Reports</div>

  <div class="right-links">
    <a href="mailto:feedback@prettyreports.com">Feedback</a>
  </div>
</section>

app/views/layouts/_header.html.erb
<div class="top-bar">
  <div class="logo" onclick="window.location='<%= root_url %>'">
  </div>
  <div class="text-logo" onclick="window.location='<%= root_url %>'">
    Pretty Reports
  </div>

  <div class="user-menu dropdown">

    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= current_user.full_name %>
    </a>
    <i class=" icon-chevron-down icon-white"></i>

    <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="drop3">
      <li><a tabindex="-1" href="<%= reports_url %>">My Reports</a></li>
      <li class="divider"></li>
      <li>
        <%= link_to 'Preferences', { :action => :edit,
          :id => current_user, :controller => "users" }, { :tabindex => "-1" } %>
      </li>
    </ul>
  </div>


  <div class="logout-container">
    <%=link_to "", {controller: "devise/sessions", action: "destroy"},
      class: "logout"%>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <%= yield :head %>

  </head>

  <%# Add custom ids and classes to the body tag %>
  <body <%= "id='#{yield :page_id}'"  %>  <%= if((yield :page_class).present?) then
      "class=#{yield :page_class}" end
  %> >

    <header id="page-header" class="js-page-header">
      <%= render 'layouts/header' %>
    </header>

    <% flash.each do |key, value| %>
      <%
        alert_class = case key
        when :alert then 'alert-error'
        when :notice then 'alert-success'
        else ''
        end
      %>
      <% unless value.blank? %>
        <div class="alert <%= alert_class %>">
          <a class="close" data-dismiss="alert" href="#">×</a>
          <%= value %>
        </div>
      <% end %>
    <% end %>

    <section id="page-content">
      <%= yield %>
    </section>

    <%= render 'layouts/footer' %>

    <div id="ajax-loading-indicator" class="alert alert-success">
      Loading...
    </div>

    <a class="beta-label">
      <span class="tag">Beta Version</span>
    </a>

  </body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <%= yield :head %>

  </head>

  <body <%= "id='#{yield :page_id}'"  %> >

    <div id="page-content">
      <% flash.each do |key, value| %>
        <%
          alert_class = case key
          when :alert then 'alert-error'
          when :notice then 'alert-success'
          else ''
          end
        %>
        <% unless value.blank? %>
          <div class="alert <%= alert_class %>">
            <a class="close" data-dismiss="alert" href="#">×</a>
            <%= value %>
          </div>
        <% end %>
      <% end %>


      <%= yield %>
    </div>

    <%= render "layouts/footer" %>

  </body>

</html>